server:
  port: 8888

spring:
  application:
    name: ead-config-server
  config:
    import: optional:file:configuracao.env[.properties]
  cloud:
    config:
      server:
        git:
          uri: https://github.com/faelaraujo/ead-config-server-repo
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}

ead:
  configServer:
    username: configserver
    password: 'ead123cs'
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost